name: jdih_kendari
description: Aplikasi mobile JDIH Kota Kendari (frontend publik).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cached_network_image: ^3.4.1
  flutter_widget_from_html_core: ^0.16.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.0
  intl: any
  pdfrx: ^2.4.7
  youtube_player_iframe: ^6.0.2
  file_saver: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "#FEFBE8"
  adaptive_icon_foreground: assets/icon/icon_fg.png

flutter_native_splash:
  color: "#FEFBE8"
  color_dark: "#111827"
  image: assets/icon/splash.png
  android_12:
    color: "#FEFBE8"
    color_dark: "#111827"
    image: assets/icon/splash.png

flutter:
  uses-material-design: true

